# -*- coding: utf-8 -*-
"""Airline Delay & Revenue Intelligence Platform

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4HeKprU378UcYlfRQ0fvD0yRhOqFXTz
"""

import pandas as pd

flights = pd.read_csv("flights.csv")
delay = pd.read_csv("delay_data.csv")
airports = pd.read_csv("airports.csv")
revenue = pd.read_csv("revenue.csv")

print(flights.head())
print(delay.head())
print(airports.head())
print(revenue.head())

print("Flights:", flights.shape)
print("Delay:", delay.shape)
print("Airports:", airports.shape)
print("Revenue:", revenue.shape)

flights["Date"] = pd.to_datetime(flights["Date"])

flights.info()

print(flights.isnull().sum())
print(delay.isnull().sum())
print(airports.isnull().sum())
print(revenue.isnull().sum())

print("Flights:", flights.duplicated().sum())
print("Delay:", delay.duplicated().sum())
print("Airports:", airports.duplicated().sum())
print("Revenue:", revenue.duplicated().sum())

merged_df = flights.merge(
    delay,
    on="Flight_ID",
    how="left"
)

merged_df = merged_df.merge(
    revenue,
    on="Flight_ID",
    how="left"
)

print(merged_df)

merged_df["Flight_ID"].nunique()

merged_df["Revenue"].sum()

merged_df["Delay_Minutes"].mean()

merged_df["Delay_Minutes"].max()

merged_df.head()
merged_df.shape

merged_df.head()
merged_df.shape

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,5))

sns.countplot(
    data=merged_df,
    x="Delay_Type",
    color='red'
)

plt.title("Number of Delays by Type")
plt.xticks(rotation=45)

plt.show()

airline_delay = merged_df.groupby(
    "Airline"
)["Delay_Minutes"].mean().reset_index()

airline_delay["Delay_Minutes"] = airline_delay["Delay_Minutes"].round(2)
airline_delay

plt.figure(figsize=(10,5))

sns.barplot(
    data=airline_delay,
    x="Airline",
    y="Delay_Minutes"
)

plt.title("Average Delay by Airline")

plt.show()

airline_revenue = merged_df.groupby(
    "Airline"
)["Revenue"].sum().reset_index()

airline_revenue

plt.figure(figsize=(10,5))

sns.barplot(
    data=airline_revenue,
    x="Airline",
    y="Revenue"
)

plt.title("Revenue by Airline")

plt.show()

route_revenue = merged_df.groupby(
    "Route"
)["Revenue"].sum().reset_index()

route_revenue = route_revenue.sort_values(
    by="Revenue",
    ascending=False
)

route_revenue

plt.figure(figsize=(12,5))

sns.barplot(
    data=route_revenue,
    x="Route",
    y="Revenue"
)

plt.title("Revenue by Route")
plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=merged_df,
    x="Delay_Minutes",
    y="Revenue",
    hue="Airline"
)

plt.title("Delay vs Revenue")

plt.show()

merged_df["Month"] = merged_df["Date"].dt.month_name()

monthly_delay = merged_df.groupby(
    "Month"
)["Delay_Minutes"].mean().reset_index()

monthly_delay

plt.figure(figsize=(12,5))

sns.lineplot(
    data=monthly_delay,
    x="Month",
    y="Delay_Minutes",
    marker="o"
)

plt.title("Monthly Average Delay Trend")

plt.xticks(rotation=45)

plt.show()

efficiency = merged_df.groupby("Airline").agg({
    "Revenue":"sum",
    "Delay_Minutes":"mean"
}).reset_index()

efficiency["Efficiency_Score"] = (
    efficiency["Revenue"] /
    efficiency["Delay_Minutes"]
)

efficiency.sort_values(
    by="Efficiency_Score",
    ascending=False,
    inplace=True
)

efficiency

plt.figure(figsize=(10,5))

sns.barplot(
    data=efficiency,
    x="Airline",
    y="Efficiency_Score"
)

plt.title("Airline Efficiency Score")

plt.show()



route_risk = merged_df.groupby("Route").agg({
    "Delay_Minutes":"mean",
    "Revenue":"sum"
}).reset_index()

route_risk["Delay_Minutes"] = route_risk["Delay_Minutes"].round(2)
route_risk

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=route_risk,
    x="Delay_Minutes",
    y="Revenue",
    s=200
)

for i in range(len(route_risk)):
    plt.text(
        route_risk["Delay_Minutes"][i],
        route_risk["Revenue"][i] + 500000, # Added a vertical offset here
        route_risk["Route"][i]
    )

plt.title("Route Risk Matrix")

plt.show()

merged_df["Revenue_Loss"] = (
    merged_df["Delay_Minutes"] * 100
)

merged_df["Revenue_Loss"].sum()

loss_airline = merged_df.groupby(
    "Airline"
)["Revenue_Loss"].sum().reset_index()

loss_airline

plt.figure(figsize=(10,5))

sns.barplot(
    data=loss_airline,
    x="Airline",
    y="Revenue_Loss",
    hue="Airline"
)

plt.title("Estimated Revenue Loss by Airline")

plt.show()

total_flights = merged_df["Flight_ID"].nunique()

total_revenue = merged_df["Revenue"].sum()

avg_delay = round(
    merged_df["Delay_Minutes"].mean(),2
)

total_loss = merged_df["Revenue_Loss"].sum()

print("Total Flights:", total_flights)
print("Total Revenue:", total_revenue)
print("Average Delay:", avg_delay)
print("Estimated Revenue Loss:", total_loss)

merged_df.to_csv(
    "airline_final_dataset.csv",
    index=False
)